- src/Agoda.Analyzers.CodeFixes/tools/install.ps1
- Add an updated script to install it VS
> Update install script to be able install analyzers in VS

- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/AG0001DependencyResolverMustNotBeUsed.cs
- src/Agoda.Analyzers/AgodaCustom/AG0002PrivateMethodsShouldNotBeTested.cs
- src/Agoda.Analyzers/AgodaCustom/AG0003HttpContextCannotBePassedAsMethodArgument.cs
- src/Agoda.Analyzers/Helpers/DescriptionContentLoader.cs
- src/Agoda.Analyzers/RuleContent/AG0001DependencyResolverMustNotBeUsed.html
- src/Agoda.Analyzers/RuleContent/AG0002PrivateMethodsShouldNotBeTested.html
- src/Agoda.Analyzers/RuleContent/AG0003HttpContextCannotBePassedAsMethodArgument.html
Add new HTML template base description for all of our rules.
> Add new html based rule description

- src/Agoda.Analyzers.CodeFixes/Agoda.Analyzers.nuspec
Add extra content files for rules
> Add missing html files from the nuspec

- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/AG0004AsyncAnalyzer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.resx
> Add async analyzer to prevent blocking calls

- src/Agoda.Analyzers.Test/AgodaCustom/AG0006UnitTests.cs
- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/AG0006ClassShouldNotHaveMoreThanOnePublicConstructor.cs
- src/Agoda.Analyzers/RuleContent/AG0006ClassShouldNotHaveMoreThanOnePublicConstructor.html
> AG0006 ClassShouldNotHaveMoreThanOnePublicConstructor

- src/Agoda.Analyzers.Test/AgodaCustom/AG0001UnitTests.cs
- src/Agoda.Analyzers.Test/AgodaCustom/AG0002UnitTests.cs
- src/Agoda.Analyzers.Test/AgodaCustom/AG0003UnitTests.cs
- src/Agoda.Analyzers.Test/AgodaCustom/AG0005UnitTests.cs
- src/Agoda.Analyzers.Test/AgodaCustom/AG0030UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0030PreventUseOfDynamics.cs
...and removing unnecessary double braces everywhere.
> Fixing bug where analyzer would fail any type containing the word "dynamic"

- src/Agoda.Analyzers.Test/AgodaCustom/AG0013UnitTests.cs
- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/AG0013LimitNumberOfTestMethodParametersTo5.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.resx
- src/Agoda.Analyzers/RuleContent/AG0013LimitNumberOfTestMethodParametersTo5.html
> AG0013: Limit number of test method input parameters to 5

- src/Agoda.Analyzers.Test/AgodaCustom/AG0023UnitTests.cs
- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/AG0023PreventUseOfThreadSleep.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.resx
- src/Agoda.Analyzers/RuleContent/AG0023PreventTheUseOfThreadSleep.html
> AG0023: Prevent use of Thread.Sleep

- src/Agoda.Analyzers.Test/AgodaCustom/AG0027UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0026EnsureOnlyCssSelectorIsUsedToFindElements.cs
- src/Agoda.Analyzers/AgodaCustom/AG0027EnsureOnlyDataSeleniumIsUsedToFindElements.cs
- src/Agoda.Analyzers/Helpers/PermittedInvocationRule.cs
- src/Agoda.Analyzers/Helpers/TestMethodHelpers.cs
> Fixing false positives for AG0027

- src/Agoda.Analyzers.Test/AgodaCustom/AG0027UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0027EnsureOnlyDataSeleniumIsUsedToFindElements.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
> Analyze compile-time constant values passed to By.CssSelector etc.

- src/Agoda.Analyzers.Test/AgodaCustom/AG0012UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0012TestMethodMustContainAtLeastOneAssertion.cs
- src/Agoda.Analyzers/Helpers/TestMethodHelpers.cs
> AG0005: Better detection of test cases

- README.md
A few typos and a sprinkling of markup.
> Editing while reading

- src/Agoda.Analyzers/AgodaCustom/AG0012TestMethodMustContainAtLeastOneAssertion.cs
- src/Agoda.Analyzers/AgodaCustom/AG0018PermitOnlyCertainPubliclyExposedEnumerables.cs
This is just code clean up, won't impact the functionality
> remove unused ref

- src/Agoda.Analyzers.Test/AgodaCustom/AG0035UnitTests.cs
- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/AG0001DependencyResolverMustNotBeUsed.cs
- src/Agoda.Analyzers/AgodaCustom/AG0011NoDirectQueryStringAccess.cs
- src/Agoda.Analyzers/AgodaCustom/AG0023PreventUseOfThreadSleep.cs
- src/Agoda.Analyzers/AgodaCustom/AG0025PreventUseOfTaskContinue.cs
- src/Agoda.Analyzers/AgodaCustom/AG0026EnsureOnlyCssSelectorIsUsedToFindElements.cs
- src/Agoda.Analyzers/AgodaCustom/AG0032PreventUseOfBlockingTaskMethods.cs
- src/Agoda.Analyzers/AgodaCustom/AG0033PreventUseOfTaskResult.cs
- src/Agoda.Analyzers/AgodaCustom/AG0035PreventUseEnvironmentMachineName.cs
- src/Agoda.Analyzers/AgodaCustom/AG0035PreventUseOfMachineName.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.resx
- src/Agoda.Analyzers/AgodaCustom/MethodInvocationAnalyzerBase.cs
- src/Agoda.Analyzers/AgodaCustom/PropertyInvocationAnalyzerBase.cs
- src/Agoda.Analyzers/Helpers/InvocationRule.cs
- src/Agoda.Analyzers/Helpers/TestMethodHelpers.cs
- src/Agoda.Analyzers/RuleContent/AG0035PreventUseOfMachineName.html
> AG0035 - Prevent use of MachineName.

- src/Agoda.Analyzers.Test/AgodaCustom/AG0037UnitTests.cs
- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/AG0035PreventUseOfMachineName.cs
- src/Agoda.Analyzers/AgodaCustom/AG0037EnsureSeleniumTestHasOwnedByAttribute.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.resx
- src/Agoda.Analyzers/RuleContent/AG0037EnsureSeleniumTestHasOwnedByAttribute.html
> AG0037: Ensure all Selenium tests have an [OwnedBy] attribute

- src/Agoda.Analyzers.CodeFixes/Agoda.Analyzers.CodeFixes.csproj
- src/Agoda.Analyzers.CodeFixes/Agoda.Analyzers.nuspec
- src/Agoda.Analyzers.Test/Agoda.Analyzers.Test.csproj
- src/Agoda.Analyzers.Test/AgodaCustom/AG0003UnitTests.cs
- src/Agoda.Analyzers.Test/AgodaCustom/AG0011UnitTests.cs
- src/Agoda.Analyzers.Test/AgodaCustom/AG0035UnitTests.cs
- src/Agoda.Analyzers.Vsix/Agoda.Analyzers.Vsix.csproj
- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
- src/Agoda.Analyzers/Helpers/DescriptionContentLoader.cs
Fixed Error on accessing the HTML, need a better solution for adding the html content to the project.
For now its removed, but the links are all populated for the online documentation so I think this will be fine for the short term.
> change target

- src/Agoda.Analyzers.Test/AgodaCustom/AG0012UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0012TestMethodMustContainAtLeastOneAssertion.cs
> AG0012: Fix nested assertions

- src/Agoda.Analyzers.Test/AgodaCustom/AG0018UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0018PermitOnlyCertainPubliclyExposedEnumerables.cs
Issue: https://github.com/agoda-com/AgodaAnalyzers/issues/156
Closes #156
> Issue-156: added IReadOnlyCollecton to allowed collections

- .github/workflows/build.yml
- src/Agoda.Analyzers.CodeFixes/Agoda.Analyzers.CodeFixes.csproj
- src/Agoda.Analyzers.CodeFixes/Properties/AssemblyInfo.cs
- src/Agoda.Analyzers/Agoda.Analyzers.csproj
- src/Agoda.Analyzers/Properties/AssemblyInfo.cs
> Fix nuget Package and CI process

- src/Agoda.Analyzers/Agoda.Analyzers.csproj
Not sure how this got in there, only needed in test project
> Remove Unneeded dependency

- doc/AG0044.md
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.resx
> AG0046 isn't needed, instead patch 44 docs

- doc/AG0047.md
- src/Agoda.Analyzers.Test/Agoda.Analyzers.Test.csproj
- src/Agoda.Analyzers.Test/AgodaCustom/AG0047UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0047TestContainerBuildOrderAnalyzer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.Designer.cs
- src/Agoda.Analyzers/AgodaCustom/CustomRulesResources.resx
- src/Agoda.Analyzers/AnalyzerReleases.Unshipped.md
> AG0047 calling TestContainer build too early.

- .github/workflows/build.yml
- src/Agoda.Analyzers.Test/Agoda.Analyzers.Test.csproj
- src/Agoda.Analyzers.Test/AgodaCustom/AG0012UnitTests.cs
- src/Agoda.Analyzers/AgodaCustom/AG0012TestMethodMustContainAtLeastOneAssertion.cs
Updated the NetCore while I was here.
> Fix AG0012 to look for generic methods as well
